stages:
  download_dataset:
    cmd: (
        wget ${data.download.url} -O ${data.download.zip_file} &&
        unzip ${data.download.zip_file} -d ${root_dir}/${data.download.subdir} &&
        rm ${data.download.zip_file}
      ) &> logs/download_dataset.out
    outs:
      - ${root_dir}/${data.download.subdir}
      - logs/download_dataset.out

  split_dataset:
    cmd: python scripts/split_dataset.py &> logs/split_dataset.out
    deps:
      - scripts/split_dataset.py
      - ${root_dir}/${data.download.subdir}
    params:
      - data.dataset.val_test_split
    outs:
      - ${root_dir}/${data.dataset.subdir}/dataset.csv
      - ${root_dir}/${data.dataset.subdir}/train
      - ${root_dir}/${data.dataset.subdir}/val
      - ${root_dir}/${data.dataset.subdir}/test
      - logs/split_dataset.out

  train:
    cmd: python scripts/train.py &> logs/train.out
    deps:
      - scripts/train.py
      - ${root_dir}/${data.dataset.subdir}/train
      - ${root_dir}/${data.dataset.subdir}/val
    params:
      - train
    outs:
      - ${root_dir}/${train.subdir}/model
      - logs/train.out
    live:
      ${root_dir}/${train.subdir}/training_metrics:
        summary: true
        html: true

  evaluate:
    cmd: python scripts/evaluate.py &> logs/evaluate.out
    deps:
      - scripts/evaluate.py
      - ${root_dir}/${data.dataset.subdir}/test
      - ${root_dir}/${train.subdir}/model
    outs:
      - logs/evaluate.out
    metrics:
      - ${root_dir}/${evaluate.subdir}/metrics.json:
          cache: false
    plots:
      - ${root_dir}/${evaluate.subdir}/predictions.csv:
          template: confusion
          x: true_label
          y: predicted_label
          title: Confusion Matrix
