root_dir: ./data

data:
  download:
    subdir: raw
    url: https://storage.googleapis.com/mledu-datasets/cats_and_dogs_filtered.zip
    zip_file: cats_and_dogs_filtered.zip
  dataset:
    subdir: dataset
    val_test_split:
      val: 0.7
      test: 0.3

train:
  batch_size: 32
  img_size: [160, 160]
  learning_rate: 0.0001
  subdir: train
  epochs:
    frozen: 10
    unfrozen: 10
  fine_tune_at: 100

model:
  # Choose among available models in tf.keras.applications
  # See https://www.tensorflow.org/api_docs/python/tf/keras/applications
  backbone: tensorflow.keras.applications.MobileNetV2
  preprocess_input: tensorflow.keras.applications.mobilenet_v2.preprocess_input

evaluate:
  subdir: evaluation
